# Read configuration information from config.ini
import configparser

config = configparser.ConfigParser()
config.read("config.ini")

CONFIG_AUTH_SECTION = "AUTHORIZATION"
SECRET_KEY = config.get(CONFIG_AUTH_SECTION, "SECRET_KEY")
ALGORITHM = config.get(CONFIG_AUTH_SECTION, "ALGORITHM") 
ACCESS_TOKEN_EXPIRE_MINUTES = int(config.get(CONFIG_AUTH_SECTION, "ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_MINUTES = int(config.get(CONFIG_AUTH_SECTION, "REFRESH_TOKEN_EXPIRE_MINUTES"))

MONGODB_SECTION = "MONGODB"
MONGODB_URL = config.get(MONGODB_SECTION, "MONGODB_URL")
MONGODB_DATABASE = config.get(MONGODB_SECTION, "MONGODB_DATABASE")